name: TestXcodegen
packages:
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    from: 2.2.3
configs:
  TestXcodegen-DEV: debug
  TestXcodegen: release
configFiles:
  TestXcodegen-DEV: Config/TestXcodegen-DEV.xcconfig
  TestXcodegen: Config/TestXcodegen.xcconfig
settings:
  base:
    # USER DEFINED PROJECT
    BUILD_NUMBER: $(BUILD_NUMBER)
    VERSION_NAME: $(VERSION_NAME)
    CURRENT_PROJECT_VERSION: $(BUILD_NUMBER)
    MARKETING_VERSION: $(VERSION_NAME)
targets:
  TestXcodegen:
    type: application
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - path: TestXcodegen
        name: TestXcodegen
    settings:
      base:
      # USER DEFINED TARGET
        INFOPLIST_FILE: TestXcodegen/Info.plist
        GENERATE_INFOPLIST_FILE: NO
      configs:
        TestXcodegen-DEV:
          PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          PRODUCT_NAME: TestXcodegen
          DEVELOPMENT_TEAM: 94XJVN3C32
        TestXcodegen:
          PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
          PRODUCT_NAME: TestXcodegen
          DEVELOPMENT_TEAM: 94XJVN3C32
    dependencies:
      - package: SDWebImageSwiftUI
schemes:
  TestXcodegen:
    build:
      targets:
        TestXcodegen: all
    run:
      config: TestXcodegen
    profile:
      config: TestXcodegen
    analyze:
      config: TestXcodegen
    archive: TestXcodegen
  TestXcodegen-DEV:
    build:
      targets:
        TestXcodegen: all
    run:
      config: TestXcodegen-DEV
    profile:
      config: TestXcodegen-DEV
    analyze:
      config: TestXcodegen-DEV
    archive:
      config: TestXcodegen-DEV
